=== cyber-dojo/secrets/docs/custom-attestation-type-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "days_since_update",
      "days_to_expiry",
      "expires_at",
      "has_github_secret",
      "has_txt_file",
      "is_secret",
      "name",
      "repo",
      "scope",
      "txt_filename",
      "updated_at"
    ],
    "properties": {
      "days_since_update": {
        "type": [
          "integer",
          "null"
        ],
        "description": "The number of days since the date in the updated_at field"
      },
      "days_to_expiry": {
        "type": "integer",
        "description": "The number of days to expiry, based on the date in the 'expires_at' field"
      },
      "expires_at": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}|never",
        "description": "The date the secret's value expires, as set in its .txt file, or 'never'"
      },
      "has_github_secret": {
        "type": "boolean"
      },
      "has_txt_file": {
        "type": "boolean"
      },
      "is_secret": {
        "type": "boolean"
      },
      "name": {
        "type": "string",
        "description": "The name of the secret, eg KOSLI_API_TOKEN"
      },
      "repo": {
        "type": "string",
        "description": "The name of the repo this secret belongs to if scope==repo"
      },
      "scope": {
        "type": "string",
        "enum": [
          "org",
          "repo"
        ]
      },
      "txt_filename": {
        "type": [
          "string",
          "null"
        ],
        "description": "The path to the .txt file containing information on the secret"
      },
      "updated_at": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}",
        "description": "The date the secret was last updated in GitHub"
      }
    }
  }
}

=== cyber-dojo/secrets/test/335_days_since_update/expected.blended.json
[
  {
    "days_since_update": 10,
    "days_to_expiry": 7,
    "expires_at": "2025-07-29",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "KOSLI_API_TOKEN_PROD",
    "repo": "server",
    "scope": "org",
    "txt_filename": "txt_root/server/gh-org-kosli-api-token.txt",
    "updated_at": "2025-07-12"
  },
  {
    "days_since_update": 335,
    "days_to_expiry": 21,
    "expires_at": "2025-08-12",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "SOME_SECRET",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": "txt_root/cli/gh-repo-some-secret.txt",
    "updated_at": "2024-08-21"
  }
]

=== cyber-dojo/secrets/test/new_org_secret_with_no_matching_secret_txt_file/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 26826,
    "expires_at": "2099-01-01",
    "has_github_secret": true,
    "has_txt_file": false,
    "is_secret": true,
    "name": "THIS_IS_A_NEW_SECRET",
    "repo": "secrets",
    "scope": "org",
    "txt_filename": null,
    "updated_at": "2025-07-08"
  }
]

=== cyber-dojo/secrets/test/repo_secret_expiring_and_needs_updating/expected.blended.json
[
  {
    "days_since_update": 359,
    "days_to_expiry": 2,
    "expires_at": "2025-07-24",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "SOME_SECRET",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": "txt_root/cli/gh-repo-some-secret.txt",
    "updated_at": "2024-07-28"
  }
]

=== cyber-dojo/secrets/test/same_secret_twice_in_api_once_in_txt_files/expected.blended.json
[
  {
    "days_since_update": 11,
    "days_to_expiry": 26826,
    "expires_at": "2099-01-01",
    "has_github_secret": true,
    "has_txt_file": false,
    "is_secret": true,
    "name": "LIST_ORG_AND_REPO_SECRETS",
    "repo": "server",
    "scope": "repo",
    "txt_filename": null,
    "updated_at": "2025-07-11"
  },
  {
    "days_since_update": 1,
    "days_to_expiry": 19,
    "expires_at": "2025-08-10",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "LIST_ORG_AND_REPO_SECRETS",
    "repo": "secrets",
    "scope": "repo",
    "txt_filename": "txt_root/secrets/gh-repo-list-org-and-repo-secrets.txt",
    "updated_at": "2025-07-21"
  },
  {
    "days_since_update": null,
    "days_to_expiry": 64,
    "expires_at": "2025-09-24",
    "has_github_secret": false,
    "has_txt_file": true,
    "is_secret": true,
    "name": "READ_GH_ISSUES",
    "repo": "server",
    "scope": "repo",
    "txt_filename": "txt_root/server/gh-repo-read-gh-issues.txt",
    "updated_at": null
  }
]

=== cyber-dojo/secrets/test/new_org_secret_with_secret_txt_file/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 2,
    "expires_at": "2025-07-24",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "THIS_IS_A_NEW_SECRET",
    "repo": "secrets",
    "scope": "org",
    "txt_filename": "txt_root/secrets/gh-org-this-is-a-new-secret.txt",
    "updated_at": "2025-07-08"
  }
]

=== cyber-dojo/secrets/test/new_repo_secret_with_matching_secret_txt_file/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 7,
    "expires_at": "2025-07-29",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "KOSLI_API_TOKEN_PROD",
    "repo": "secrets",
    "scope": "org",
    "txt_filename": "txt_root/secrets/gh-org-kosli-api-token.txt",
    "updated_at": "2025-07-08"
  },
  {
    "days_since_update": 14,
    "days_to_expiry": 21,
    "expires_at": "2025-08-12",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "THIS_IS_A_NEW_SECRET",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": "txt_root/cli/gh-repo-this-is-a-new-secret.txt",
    "updated_at": "2025-07-08"
  }
]

=== cyber-dojo/secrets/test/ignore_kosli_reporter_sources/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 2,
    "expires_at": "2025-07-24",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": false,
    "name": "KOSLI_REPORTER_SOURCES_AWS_REGION",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": "txt_root/cli/gh-repo-kosli-reporter-sources-aws-region.txt",
    "updated_at": "2025-07-08"
  }
]

=== cyber-dojo/secrets/test/org_txt_file_has_no_corresponding_gh_secret/expected.blended.json
[
  {
    "days_since_update": null,
    "days_to_expiry": 7,
    "expires_at": "2025-07-29",
    "has_github_secret": false,
    "has_txt_file": true,
    "is_secret": true,
    "name": "KOSLI_API_TOKEN_PROD",
    "repo": "secrets",
    "scope": "org",
    "txt_filename": "txt_root/secrets/gh-org-kosli-api-token.txt",
    "updated_at": null
  }
]
