=== cyber-dojo/secrets/docs/custom-attestation-type-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "days_since_update",
      "days_to_expiry",
      "expires_at",
      "has_github_secret",
      "has_txt_file",
      "is_secret",
      "name",
      "repo",
      "scope",
      "txt_filename",
      "updated_at"
    ],
    "properties": {
      "days_since_update": {
        "type": [
          "integer",
          "null"
        ],
        "description": "The number of days since the date in the updated_at field"
      },
      "days_to_expiry": {
        "type": "integer",
        "description": "The number of days to expiry, based on the date in the 'expires_at' field"
      },
      "expires_at": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}|never",
        "description": "The date the secret's value expires, as set in its .txt file, or 'never'"
      },
      "has_github_secret": {
        "type": "boolean"
      },
      "has_txt_file": {
        "type": "boolean"
      },
      "is_secret": {
        "type": "boolean"
      },
      "name": {
        "type": "string",
        "description": "The name of the secret, eg KOSLI_API_TOKEN"
      },
      "repo": {
        "type": "string",
        "description": "The name of the repo this secret belongs to if scope==repo"
      },
      "scope": {
        "type": "string",
        "enum": [
          "org",
          "repo"
        ]
      },
      "txt_filename": {
        "type": [
          "string",
          "null"
        ],
        "description": "The path to the .txt file containing information on the secret"
      },
      "updated_at": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}",
        "description": "The date the secret was last updated in GitHub"
      }
    }
  }
}

=== cyber-dojo/secrets/test/two_identical_repo_secrets/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 23,
    "expires_at": "2025-08-14",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "KOSLI_API_TOKEN_PROD",
    "repo": "server",
    "scope": "org",
    "txt_filename": "txt_root/server/gh-org-kosli-api-token.txt",
    "updated_at": "2025-07-08"
  },
  {
    "days_since_update": 14,
    "days_to_expiry": 32,
    "expires_at": "2025-08-23",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "WIBBLE",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": "txt_root/cli/gh-repo-wibble.txt",
    "updated_at": "2025-07-08"
  },
  {
    "days_since_update": 14,
    "days_to_expiry": 26826,
    "expires_at": "2099-01-01",
    "has_github_secret": true,
    "has_txt_file": false,
    "is_secret": true,
    "name": "WIBBLE",
    "repo": "terraform",
    "scope": "repo",
    "txt_filename": null,
    "updated_at": "2025-07-08"
  }
]

=== cyber-dojo/secrets/test/new_repo_secret_with_no_secret_txt_file/expected.blended.json
[
  {
    "days_since_update": 14,
    "days_to_expiry": 7,
    "expires_at": "2025-07-29",
    "has_github_secret": true,
    "has_txt_file": true,
    "is_secret": true,
    "name": "KOSLI_API_TOKEN_PROD",
    "repo": "secrets",
    "scope": "org",
    "txt_filename": "txt_root/secrets/gh-org-kosli-api-token.txt",
    "updated_at": "2025-07-08"
  },
  {
    "days_since_update": 14,
    "days_to_expiry": 26826,
    "expires_at": "2099-01-01",
    "has_github_secret": true,
    "has_txt_file": false,
    "is_secret": true,
    "name": "FOOBAR",
    "repo": "cli",
    "scope": "repo",
    "txt_filename": null,
    "updated_at": "2025-07-08"
  }
]
